### PR TITLE
Python CI

### PR DESCRIPTION
**Pull request by marktsuchida**

### CODE REVIEW

**Comment by marktsuchida** [comment]
Note this builds and tests but does not yet publish to PyPI.

**Comment by ctrueden** [comment]
> does not yet publish to PyPI.

For the PyImageJ software stack, we are still doing publication manually using twine from a local workstation. How are you thinking of having the CI publish, @marktsuchida? Would you make a bot account for PyPI, add it to the flimlib project on PyPI, and give the deploy credentials as a secret to the flimlib org on GitHub? Or would you let the CI publish as you? If the former, would it make sense for this bot account to be shared between flimlib, scijava, imglib, and imagej orgs? For e.g. AppVeyor I named such an account `scijava-ci`, but that name is a bit strange when publishing our python-based projects. If only we had an umbrella term for all this work, but without "java" in the name... imagesc-ci? But that's maybe a bit presumptuous?

**Comment by marktsuchida** [comment]
On PyPI, the usual way is to only create human users. There is no concept of an org, but you can give multiple people access to a project (and they are shown as maintainers on the project page).

Any of the maintainers can then create a (non-human) access token, which can have access to all projects you maintain, or just one. The latter type can only be created if the project already exists, so cannot be used for the first release (because the project doesn't exist until its first file is uploaded, thereby creating the first release -- no squatting possible).

So my usual approach is:
1. Create an access token with access to all my projects and set it as a GH Actions secret (at the repo level)
1. Perform the first release of the project
1. Delete the just-used access token from PyPI
1. Create a new access token with access restricted to the single project
1. Set the project-specific token as the GH Actions secret

(You would need to trust the other members of the GH repo/org not to do bad things with your all-projects token during the short time that it is available as a secret. Or you could do the first release on your local machine.)

As far as I can tell, there is no (visible) record of who (or which token) uploaded a given file or release, so creating a bot doesn't really gain you anything presentation-wise. Because tokens are easy to create, I never record them anywhere after pasting into GitHub; I can create new ones if I need to re-enter the secret for CI.

If you want to be able to have a single GitHub org-level secret (for the main benefit of not having to create one for each repo), then I guess you would need to create a bot account for the sole purpose of scoping the access to the desired set of projects (although nonexistent projects will always be accessible). And by performing the first release of a new project using the bot's token, the project will be "maintained" by the bot. But then you'd have to manually log in as the bot to add human maintainers. I haven't been in this situation because I only have a couple of PyPI projects so far.

Working examples: [cjdk](https://github.com/cachedjdk/cjdk/blob/8ad954c8f8652c33058b098ff54b89f58039e903/.github/workflows/ci.yml#L119) and [pymmcore](https://github.com/micro-manager/pymmcore/blob/5fb6ad14a57d2b10b57d04bc7706ff56f1162c9c/.github/workflows/build.yml#L32).

**Comment by marktsuchida** [comment]
> there is no (visible) record of who (or which token) uploaded a given file or release

Actually it's visible if you log in and go to the project's security history. But it's not publicly visible.

**Pull request merged**
